### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by merriam** [zippyui/react-scheduler#1]
I'm confused.  Your package.json says "commercial" license.  Your LICENSE file says MIT?

**Comment by radubrehar** [comment]
It's MIT.
This repo is empty for now. Specifically, it will contain a very carefully configured https://github.com/zippyui/react-date-picker, tailored for scheduling activities.

**Comment by merriam** [comment]
Cool!  Good luck!  In Python, we use FullCalendar.
